<html>
<head>
<script type="text/javascript" src="../http/tests/inspector-protocol/resources/protocol-test.js"></script>
<script>
function test()
{
    try {
        new InspectorTest.AsyncTestSuite();
        InspectorTest.log("FAIL: instantiating AsyncTestSuite requires name argument.");
    } catch (e) {
        InspectorTest.log("PASS: instantiating AsyncTestSuite requires name argument.");
    }

    try {
        new InspectorTest.AsyncTestSuite({});
        InspectorTest.log("FAIL: instantiating AsyncTestSuite requires string name argument.");
    } catch (e) {
        InspectorTest.log("PASS: instantiating AsyncTestSuite requires string name argument.");
    }

    var badArgsSuite = new InspectorTest.AsyncTestSuite("dummy");
    try {
        badArgsSuite.addTestCase();
        InspectorTest.log("FAIL: should not be able to add empty test case.");
    } catch (e) {
        InspectorTest.log("PASS: should not be able to add empty test case.");
    }
    try {
        badArgsSuite.addTestCase("string");
        InspectorTest.log("FAIL: should not be able to add non-object test case.");
    } catch (e) {
        InspectorTest.log("PASS: should not be able to add non-object test case.");
    }
    try {
        badArgsSuite.addTestCase({
            name: {},
            test: function() {},
        });
        InspectorTest.log("FAIL: test case should require string name.");
    } catch (e) {
        InspectorTest.log("PASS: test case should require string name.");
    }
    try {
        badArgsSuite.addTestCase({
            name: "foo",
            test: null,
        });
        InspectorTest.log("FAIL: test case should require test function.");
    } catch (e) {
        InspectorTest.log("PASS: test case should require test function.");
    }

    var runEmptySuite = new InspectorTest.AsyncTestSuite("AsyncTestSuite.RunEmptySuite");
    try {
        runEmptySuite.runTestCases();
        InspectorTest.log("FAIL: should not be able to run empty test suite.");
    } catch (e) {
        InspectorTest.log("PASS: should not be able to run empty test suite.");
    }

    var runTwiceSuite = new InspectorTest.AsyncTestSuite("AsyncTestSuite.RunTwiceSuite");
    runTwiceSuite.addTestCase({
        name: "DummyTest0",
        description: "Check that a suite can't run more than once.",
        test: function(resolve, reject) {
            resolve();
        }
    });

    var result = runTwiceSuite.runTestCases();
    try {
        // Test cases won't run in this event loop; this call should still throw.
        // Later tests are chained to this suite to avoid nondeterminism.
        runTwiceSuite.runTestCases();
        InspectorTest.log("FAIL: should not be able to run a test suite twice.");
    } catch (e) {
        InspectorTest.log("PASS: should not be able to run a test suite twice.");
    }

    var rejectToken = {"token": 666};
    var thrownError = new Error(rejectToken);

    var sequentialExecutionSuite = new InspectorTest.AsyncTestSuite("AsyncTestSuite.SequentialExecution");
    sequentialExecutionSuite.addTestCase({
        name: "DummyTest1",
        description: "Check test case execution order.",
        test: function(resolve, reject) {
            resolve();
        }
    });
    sequentialExecutionSuite.addTestCase({
        name: "DummyTest2",
        description: "Check test case execution order.",
        test: function(resolve, reject) {
            resolve();
        }
    });
    sequentialExecutionSuite.addTestCase({
        name: "DummyTest3",
        description: "Check test case execution order.",
        test: function(resolve, reject) {
            resolve();
        }
    });
    sequentialExecutionSuite.addTestCase({
        name: "FailingTest4",
        description: "Check that test fails by throwing an Error instance.",
        test: function(resolve, reject) {
            throw thrownError;
        }
    });

    var abortOnFailureSuite = new InspectorTest.AsyncTestSuite("AsyncTestSuite.AbortOnFailure");
    abortOnFailureSuite.addTestCase({
        name: "PassingTest5",
        description: "This test is a dummy.",
        test: function(resolve, reject) {
            resolve();
        }
    });
    abortOnFailureSuite.addTestCase({
        name: "FailingTest6",
        description: "This test should fail by explicitly calling the `reject` callback.",
        test: function(resolve, reject) {
            reject(rejectToken);
        }
    });
    abortOnFailureSuite.addTestCase({
        name: "PassingTest7",
        description: "This test should not executed when the preceding test fails.",
        test: function(resolve, reject) {
            resolve();
        }
    });

    result = result.then(function() {
        var promise = sequentialExecutionSuite.runTestCases();
        InspectorTest.assert(result instanceof Promise, "AsyncTestSuite.RunTestCases() should return a Promise.");
        return promise;
    });
    result = result.then(function resolved() {
        InspectorTest.log("FAIL: Promise from sequentialExecutionSuite.runTestCases() should reject when a test case fails.");
        return Promise.resolve(); // Continue this test.
    }, function rejected(e) {
        InspectorTest.log("PASS: Promise from sequentialExecutionSuite.runTestCases() should reject when a test case fails.");
        InspectorTest.assert(e === thrownError, "Promise from sequentialExecutionSuite.runTestCases() should reject without altering its result value.");

        InspectorTest.assert(sequentialExecutionSuite.runCount === 4, "sequentialExecutionSuite should have executed four tests.");
        InspectorTest.assert(sequentialExecutionSuite.passCount === 3, "sequentialExecutionSuite should have passed three tests.");
        InspectorTest.assert(sequentialExecutionSuite.failCount === 1, "sequentialExecutionSuite should have failed 1 test.");
        InspectorTest.assert(sequentialExecutionSuite.skipCount === 0, "sequentialExecutionSuite should have skipped zero tests.");
        return Promise.resolve(); // Continue this test.
    });

    result = result.then(function() {
        return abortOnFailureSuite.runTestCases();
    }).then(function resolved() {
        InspectorTest.log("FAIL: Promise from abortOnFailureSuite.runTestCases() should reject when a test case fails.");
        return Promise.resolve(); // Continue this test.
    }, function rejected(e) {
        InspectorTest.log("PASS: Promise from abortOnFailureSuite.runTestCases() should reject when a test case fails.");
        InspectorTest.assert(e === rejectToken, "Promise from abortOnFailureSuite.runTestCases() should reject without altering its result value.");
        InspectorTest.assert(abortOnFailureSuite.runCount === 2, "abortOnFailureSuite should have executed two tests.");
        InspectorTest.assert(abortOnFailureSuite.passCount === 1, "abortOnFailureSuite should have passed one test.");
        InspectorTest.assert(abortOnFailureSuite.failCount === 1, "abortOnFailureSuite should have failed one test.");
        InspectorTest.assert(abortOnFailureSuite.skipCount === 1, "abortOnFailureSuite should have skipped one test.");

        return Promise.resolve(); // Continue this test.
    });

    // This will finish the test whether the chain was resolved or rejected.
    result = result.then(function() { InspectorTest.completeTest(); });
}
</script>
</head>
<body onLoad="runTest()">
</body>
</html>
